import HouchiMap from "../models/HouchiMap";
import OperationOption from "../models/OperationOption";
import Turn from "../models/Turn";

export const HOUCHI_KEIKOKU_MAPS: HouchiMap[] = [
  {
    id: "kiyuushuu",
    name: "冀幽州",
    yomi: "きゆうしゅう",
    houchiCastles: [
      {
        id: "kiyuushuu-joutou",
        level: 3,
        name: "上党",
        yomi: "じょうとう",
      },
      {
        id: "kiyuushuu-gyoujou",
        level: 2,
        name: "ギョウ城",
        yomi: "ぎょうじょう",
      },
      {
        id: "kiyuushuu-kyoroku",
        level: 2,
        name: "巨鹿",
        yomi: "きょろく",
      },
      {
        id: "kiyuushuu-kanto",
        level: 2,
        name: "官渡",
        yomi: "かんと",
      },
      {
        id: "kiyuushuu-heigen",
        level: 2,
        name: "平原",
        yomi: "へいげん",
      },
      {
        id: "kiyuushuu-daigun",
        level: 2,
        name: "代郡",
        yomi: "だいぐん",
      },
      {
        id: "kiyuushuu-jouhei",
        level: 2,
        name: "襄平",
        yomi: "じょうへい",
      },
      {
        id: "kiyuushuu-kyuugen",
        level: 1,
        name: "九原",
        yomi: "きゅうげん",
      },
      {
        id: "kiyuushuu-shinyou",
        level: 1,
        name: "晋陽",
        yomi: "しんよう",
      },
      {
        id: "kiyuushuu-kokan",
        level: 1,
        name: "壺関",
        yomi: "こかん",
      },
      {
        id: "kiyuushuu-kouzan",
        level: 1,
        name: "恒山",
        yomi: "こうざん",
      },
      {
        id: "kiyuushuu-seiga",
        level: 1,
        name: "清河",
        yomi: "せいが",
      },
      {
        id: "kiyuushuu-kaikyou",
        level: 1,
        name: "界橋",
        yomi: "かいきょう",
      },
      {
        id: "kiyuushuu-nanpi",
        level: 1,
        name: "南皮",
        yomi: "なんぴ",
      },
      {
        id: "kiyuushuu-hakuba",
        level: 1,
        name: "白馬",
        yomi: "はくば",
      },
      {
        id: "kiyuushuu-enshin",
        level: 1,
        name: "延津",
        yomi: "えんしん",
      },
      {
        id: "kiyuushuu-hanyou",
        level: 1,
        name: "范陽",
        yomi: "はんよう",
      },
      {
        id: "kiyuushuu-houkuhei",
        level: 1,
        name: "北平",
        yomi: "ほくへい",
      },
      {
        id: "kiyuushuu-rinshi",
        level: 1,
        name: "臨シ",
        yomi: "りんし",
      },
      {
        id: "kiyuushuu-keijou",
        level: 1,
        name: "薊城",
        yomi: "けいじょう",
      },
      {
        id: "kiyuushuu-ryoutou",
        level: 1,
        name: "遼東",
        yomi: "りょうとう",
      },
      {
        id: "kiyuushuu-hokkai",
        level: 1,
        name: "北海",
        yomi: "ほっかい",
      },
      {
        id: "kiyuushuu-rakurou",
        level: 1,
        name: "楽浪",
        yomi: "らくろう",
      },
      {
        id: "kiyuushuu-seikyuu",
        level: 1,
        name: "青丘",
        yomi: "せいきゅう",
      },
    ],
  },
  {
    id: "seiyoshuu",
    name: "青豫州",
    yomi: "せいよしゅう",
    houchiCastles: [
      {
        id: "seiyoshuu-kyoshou",
        level: 3,
        name: "許昌",
        yomi: "きょしょう",
      },
      {
        id: "seiyoshuu-jushun",
        level: 2,
        name: "寿春",
        yomi: "じゅしゅん",
      },
      {
        id: "seiyoshuu-shouken",
        level: 2,
        name: "ショウ県",
        yomi: "しょうけん",
      },
      {
        id: "seiyoshuu-bokuyou",
        level: 2,
        name: "濮陽",
        yomi: "ぼくよう",
      },
      {
        id: "seiyoshuu-eisen",
        level: 2,
        name: "潁川",
        yomi: "えいせん",
      },
      {
        id: "seiyoshuu-kahi",
        level: 2,
        name: "下ヒ",
        yomi: "かひ",
      },
      {
        id: "seiyoshuu-chinryuu",
        level: 1,
        name: "陳留",
        yomi: "ちんりゅう",
      },
      { id: "seiyoshuu-jonan", level: 1, name: "汝南", yomi: "じょなん" },
      { id: "seiyoshuu-sekitei", level: 1, name: "石亭", yomi: "せきてい" },
      { id: "seiyoshuu-gouhi", level: 1, name: "合肥", yomi: "ごうひ" },
      { id: "seiyoshuu-taizan", level: 1, name: "泰山", yomi: "たいざん" },
      { id: "seiyoshuu-shouhai", level: 1, name: "小沛", yomi: "しょうはい" },
      { id: "seiyoshuu-houjou", level: 1, name: "彭城", yomi: "ほうじょう" },
      { id: "seiyoshuu-rokou", level: 1, name: "蘆江", yomi: "ろこう" },
      {
        id: "seiyoshuu-jushukou",
        level: 1,
        name: "濡須口",
        yomi: "じゅしゅこう",
      },
      { id: "seiyoshuu-waiin", level: 1, name: "淮陰", yomi: "わいいん" },
      { id: "seiyoshuu-kouryou", level: 1, name: "広陵", yomi: "こうりょう" },
      { id: "seiyoshuu-hourai", level: 1, name: "蓬莱", yomi: "ほうらい" },
      { id: "seiyoshuu-rouya", level: 1, name: "琅ヤ", yomi: "ろうや" },
    ],
  },
  {
    id: "keiyoushuu",
    name: "荆揚州",
    yomi: "けいようしゅう",
    houchiCastles: [
      {
        id: "keiyoushuu-jouyou",
        level: 3,
        name: "襄陽",
        yomi: "じょうよう",
      },
      {
        id: "keiyoushuu-kouryou",
        level: 2,
        name: "江陵",
        yomi: "こうりょう",
      },
      { id: "keiyoushuu-chousa", level: 2, name: "長沙", yomi: "ちょうさ" },
      { id: "keiyoushuu-kouka", level: 2, name: "江夏", yomi: "こうか" },
      {
        id: "keiyoushuu-kengeyou",
        level: 2,
        name: "建業",
        yomi: "けんぎょう",
      },
      { id: "keiyoushuu-kenan", level: 2, name: "建安", yomi: "けんあん" },
      { id: "keiyoushuu-koshi", level: 1, name: "交趾", yomi: "こうし" },
      { id: "keiyoushuu-iryo", level: 1, name: "夷陵", yomi: "いりょう" },
      { id: "keiyoushuu-buryo", level: 1, name: "武陵", yomi: "ぶりょう" },
      { id: "keiyoushuu-eian", level: 1, name: "永安", yomi: "えいあん" },
      { id: "keiyoushuu-reiryo", level: 1, name: "零陵", yomi: "れいりょう" },
      { id: "keiyoushuu-bakujo", level: 1, name: "麦城", yomi: "ばくじょう" },
      { id: "keiyoushuu-keiyo", level: 1, name: "桂陽", yomi: "けいよう" },
      { id: "keiyoushuu-koyo", level: 1, name: "衡陽", yomi: "こうよう" },
      { id: "keiyoushuu-shinya", level: 1, name: "新野", yomi: "しんや" },
      { id: "keiyoushuu-yosho", level: 1, name: "豫章", yomi: "よしょう" },
      { id: "keiyoushuu-kayo", level: 1, name: "華容", yomi: "かよう" },
      { id: "keiyoushuu-saiyo", level: 1, name: "柴桑", yomi: "さいよう" },
      { id: "keiyoushuu-sogo", level: 1, name: "蒼梧", yomi: "そうご" },
      { id: "keiyoushuu-kyokua", level: 1, name: "曲阿", yomi: "きょくあ" },
      { id: "keiyoushuu-gogun", level: 1, name: "呉郡", yomi: "ごぐん" },
      { id: "keiyoushuu-rinkai", level: 1, name: "臨海", yomi: "りんかい" },
      { id: "keiyoushuu-kaikei", level: 1, name: "会稽", yomi: "かいけい" },
    ],
  },
  {
    id: "ryouekishuu",
    name: "涼益州",
    yomi: "りょうえきしゅう",
    houchiCastles: [
      {
        id: "ryouekishuu-chouan",
        level: 3,
        name: "長安",
        yomi: "ちょうあん",
      },
      { id: "ryouekishuu-chinso", level: 2, name: "陳倉", yomi: "ちんそう" },
      { id: "ryouekishuu-kenkaku", level: 2, name: "剣閣", yomi: "けんかく" },
      { id: "ryouekishuu-furyo", level: 2, name: "フ陵", yomi: "ふりょう" },
      { id: "ryouekishuu-seito", level: 2, name: "成都", yomi: "せいと" },
      { id: "ryouekishuu-seihei", level: 1, name: "西平", yomi: "せいへい" },
      { id: "ryouekishuu-bui", level: 1, name: "武威", yomi: "ぶい" },
      { id: "ryouekishuu-gaitei", level: 1, name: "街亭", yomi: "がいてい" },
      {
        id: "ryouekishuu-gojogen",
        level: 1,
        name: "五丈原",
        yomi: "ごじょうげん",
      },
      { id: "ryouekishuu-fufu", level: 1, name: "扶風", yomi: "ふふう" },
      { id: "ryouekishuu-tensui", level: 1, name: "天水", yomi: "てんすい" },
      { id: "ryouekishuu-antei", level: 1, name: "安定", yomi: "あんてい" },
      { id: "ryouekishuu-buto", level: 1, name: "武都", yomi: "ぶと" },
      { id: "ryouekishuu-kizan", level: 1, name: "岐山", yomi: "きざん" },
      {
        id: "ryouekishuu-menchikukan",
        level: 1,
        name: "綿竹関",
        yomi: "めんちくかん",
      },
      { id: "ryouekishuu-shito", level: 1, name: "梓潼", yomi: "しとう" },
      { id: "ryouekishuu-kanka", level: 1, name: "漢嘉", yomi: "かんか" },
      { id: "ryouekishuu-kennei", level: 1, name: "建寧", yomi: "けんねい" },
      { id: "ryouekishuu-koshu", level: 1, name: "江州", yomi: "こうしゅう" },
      { id: "ryouekishuu-eisho", level: 1, name: "永昌", yomi: "えいしょう" },
      { id: "ryouekishuu-unnan", level: 1, name: "雲南", yomi: "うんなん" },
      { id: "ryouekishuu-koko", level: 1, name: "興古", yomi: "こうこ" },
    ],
  },
  {
    id: "outoken",
    name: "王都圈",
    yomi: "おうとけん",
    houchiCastles: [
      {
        id: "outoken-rakuyou",
        level: 3,
        name: "洛陽",
        yomi: "らくよう",
      },
      { id: "outoken-kanchu", level: 2, name: "漢中", yomi: "かんちゅう" },
      { id: "outoken-joyo", level: 2, name: "上庸", yomi: "じょうよう" },
      {
        id: "outoken-kankokukan",
        level: 2,
        name: "函谷関",
        yomi: "かんこくかん",
      },
      { id: "outoken-bukan", level: 2, name: "武関", yomi: "ぶかん" },
      {
        id: "outoken-shisuikan",
        level: 2,
        name: "汜水関",
        yomi: "しすいかん",
      },
      { id: "outoken-korokan", level: 2, name: "虎牢関", yomi: "ころうかん" },
      { id: "outoken-kazan", level: 1, name: "崋山", yomi: "かざん" },
      { id: "outoken-seijo", level: 1, name: "西城", yomi: "せいじょう" },
      { id: "outoken-kato", level: 1, name: "河東", yomi: "かとう" },
      { id: "outoken-dokan", level: 1, name: "潼関", yomi: "どうかん" },
      { id: "outoken-keiyo", level: 1, name: "ケイ陽", yomi: "けいよう" },
      { id: "outoken-kono", level: 1, name: "弘農", yomi: "こうのう" },
      { id: "ryouekishuu-kadai", level: 1, name: "河内", yomi: "かだい" },
      { id: "ryouekishuu-enjo", level: 1, name: "宛城", yomi: "えんじょう" },
      { id: "ryouekishuu-hanjo", level: 1, name: "樊城", yomi: "はんじょう" },
      { id: "ryouekishuu-suzan", level: 1, name: "嵩山", yomi: "すうざん" },
      { id: "ryouekishuu-royo", level: 1, name: "魯陽", yomi: "ろよう" },
    ],
  },
];

export const HOUCHI_GUNYU_MAPS: HouchiMap[] = [
  {
    id: "gunyuu",
    name: "群雄争覇",
    yomi: "ぐんゆうそうは",
    houchiCastles: [
      {
        id: "gunyuu-rakuyou",
        level: 3,
        name: "洛陽",
        yomi: "らくよう",
      },
      {
        id: "gunyuu-chouan",
        level: 2,
        name: "長安",
        yomi: "ちょうあん",
      },
      {
        id: "gunyuu-joutou",
        level: 2,
        name: "上党",
        yomi: "じょうとう",
      },
      {
        id: "gunyuu-jouyou",
        level: 2,
        name: "襄陽",
        yomi: "じょうよう",
      },
      {
        id: "gunyuu-kyoshou",
        level: 2,
        name: "許昌",
        yomi: "きょしょう",
      },
      { id: "gunyuu-heigen", level: 1, name: "平原", yomi: "へいげん" },
      { id: "gunyuu-shohai", level: 1, name: "小沛", yomi: "しょうはい" },
      { id: "gunyuu-kanchu", level: 1, name: "漢中", yomi: "かんちゅう" },
      { id: "gunyuu-roko", level: 1, name: "盧江", yomi: "ろこう" },
      { id: "gunyuu-antei", level: 1, name: "安定", yomi: "あんてい" },
      { id: "gunyuu-tensui", level: 1, name: "天水", yomi: "てんすい" },
      { id: "gunyuu-koshu", level: 1, name: "江州", yomi: "こうしゅう" },
      { id: "gunyuu-shinyo", level: 1, name: "晋陽", yomi: "しんよう" },
      { id: "gunyuu-hokuhei", level: 1, name: "北平", yomi: "ほくへい" },
      { id: "gunyuu-chosa", level: 1, name: "長沙", yomi: "ちょうさ" },
      { id: "gunyuu-kengyo", level: 1, name: "建業", yomi: "けんぎょう" },
      { id: "gunyuu-nanhi", level: 1, name: "南皮", yomi: "なんひ" },
      { id: "gunyuu-bui", level: 1, name: "武威", yomi: "ぶい" },
      { id: "gunyuu-hokkai", level: 1, name: "北海", yomi: "ほっかい" },
      { id: "gunyuu-seito", level: 1, name: "成都", yomi: "せいと" },
      { id: "gunyuu-gogun", level: 1, name: "呉都", yomi: "ごぐん" },
    ],
  },
];

export const HOUCHI_MAPS: HouchiMap[] = [
  ...HOUCHI_KEIKOKU_MAPS,
  ...HOUCHI_GUNYU_MAPS,
];

export const TURN_LIST: Turn[] = [
  {
    id: "offence",
    name: "攻城",
    text: "攻城",
  },
  {
    id: "deffence",
    name: "防衛",
    text: "防衛",
  },
  {
    id: "counterattack",
    name: "反攻",
    text: "反攻",
  },
  {
    id: "offence-without-time",
    name: "攻城（時間指示なし）",
    text: "攻城",
  },
  {
    id: "deffence-without-time",
    name: "防衛（時間指示なし）",
    text: "防衛",
  },
  {
    id: "counterattack-without-time",
    name: "反攻（時間指示なし）",
    text: "反攻",
  },
  {
    id: "relinquish",
    name: "捨て",
    text: "捨て",
  },
  {
    id: "salted",
    name: "塩漬け",
    text: "塩漬け",
  },
  {
    id: "ignore",
    name: "放置",
    text: "放置",
  },
  {
    id: "free",
    name: "フリー入力",
    text: "",
  },
];

export const OPERATION_OPTION_LIST: OperationOption[] = [
  {
    id: "no-options",
    text: "オプションなし",
  },
  {
    id: "with-debuff",
    text: "デバフあり",
  },
  {
    id: "without-debuff",
    text: "デバフなし",
  },
  {
    id: "with-mainstay",
    text: "主力あり",
  },
  {
    id: "without-mainstay",
    text: "主力なし",
  },
];

const DataList = {
  HOUCHI_KEIKOKU_MAPS,
  HOUCHI_GUNYU_MAPS,
  HOUCHI_MAPS,
  TURN_LIST,
  OPERATION_OPTION_LIST,
};

export default DataList;
